### ISSUE TITLE
temperature sensor ?

### ISSUE THREAD

**Issue by Kristian8606** [younghyunjo/esp32-homekit#12]
Congratulations on the good project!
I'm not a good programmer yet, but I've done yours project and I really enjoyed it.
I hope we will soon see a project like a temperature sensor or a colored strip.
Excuse me for my bad English.

**Comment by younghyunjo** [comment]
@Kristian8606 

Thanks for have a interests about my code.
I ordered temperature, humidity sensor(DHT22) at Aliexpress.
It`s delivering now.

After I stabilize my code, i have a plan to make a temperature example.
Please watch the enhancement of my code, and wait until I make it.

Thanks :)

**Comment by Kristian8606** [comment]
I'm not sure my question is if it's about this topic but I will ask it here.
To esp32 i have attached an LED to lights at night, but in the morning it is off.
I'll try to monitor it with a monitor to see why it's off.
What can be the problem, do you have such case?
