### ISSUE TITLE
Enhance stability

### ISSUE THREAD

**Issue by younghyunjo** [younghyunjo/esp32-homekit#13]
- [ ] Send event response to every ios devices
- [ ] Prevent CPU exception

**Comment by younghyunjo** [comment]
@streicherlouw 

I modify code for debugging send event response to every is devices.
Would you test my code?
It is committed at master branch now.

**Comment by streicherlouw** [comment]
Hi.

It works perfectly now! I can add the switch on one iPad and then the configuration automatically propagates to all the other iPads and phones, and I can set it through the external home hub from the 4G network.

Thanks for the update, it is very useful.

Here is the log:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5656
load:0x40078000,len:0
ho 12 tail 0 room 4
load:0x40078000,len:14008
entry 0x4007860c
[0;32mI (30) boot: ESP-IDF v3.1-dev-826-g4e982d4b 2nd stage bootloader[0m
[0;32mI (30) boot: compile time 09:24:41[0m
[0;32mI (30) boot: Enabling RNG early entropy source...[0m
[0;32mI (36) boot: SPI Speed      : 40MHz[0m
[0;32mI (40) boot: SPI Mode       : DIO[0m
[0;32mI (44) boot: SPI Flash Size : 4MB[0m
[0;32mI (49) boot: Partition Table:[0m
[0;32mI (52) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (59) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (67) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (74) boot:  2 factory          factory app      00 00 00010000 00100000[0m
[0;32mI (82) boot: End of partition table[0m
[0;32mI (86) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x1be78 (114296) map[0m
[0;32mI (135) esp_image: segment 1: paddr=0x0002bea0 vaddr=0x3ffb0000 size=0x03790 ( 14224) load[0m
[0;32mI (141) esp_image: segment 2: paddr=0x0002f638 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (142) esp_image: segment 3: paddr=0x0002fa40 vaddr=0x40080400 size=0x005d0 (  1488) load[0m
[0;32mI (151) esp_image: segment 4: paddr=0x00030018 vaddr=0x400d0018 size=0x817e4 (530404) map[0m
[0;32mI (345) esp_image: segment 5: paddr=0x000b1804 vaddr=0x400809d0 size=0x0ecb0 ( 60592) load[0m
[0;32mI (371) esp_image: segment 6: paddr=0x000c04bc vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;32mI (380) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (380) boot: Disabling RNG early entropy source...[0m
[0;32mI (382) cpu_start: Pro cpu up.[0m
[0;32mI (386) cpu_start: Starting app cpu, entry point is 0x40080f74[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (397) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (403) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[0;32mI (409) heap_init: At 3FFB9A38 len 000265C8 (153 KiB): DRAM[0m
[0;32mI (416) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (422) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (428) heap_init: At 4008F680 len 00010980 (66 KiB): IRAM[0m
[0;32mI (435) cpu_start: Pro cpu start user code[0m
[0;32mI (117) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
I (228) wifi: wifi firmware version: c09b606
I (228) wifi: config NVS flash: enabled
I (228) wifi: config nano formating: disabled
[0;32mI (228) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (238) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (258) wifi: Init dynamic tx buffer num: 32
I (268) wifi: Init data frame dynamic rx buffer num: 32
I (268) wifi: Init management frame dynamic rx buffer num: 32
I (268) wifi: wifi driver task: 3ffc0f40, prio:23, stack:4096
I (268) wifi: Init static rx buffer num: 10
I (278) wifi: Init dynamic rx buffer num: 32
[0;32mI (378) phy: phy_version: 386.0, 67c798f, Mar 14 2018, 16:34:06, 0, 0[0m
I (378) wifi: mode : sta (30:ae:a4:21:16:0c)
[0;32mI (378) SWITCH: wifi_init_sta finished.[0m
[0;32mI (378) SWITCH: connect to ap SSID:STL password:*******[0m
I (498) wifi: n:11 0, o:1 0, ap:255 255, sta:11 0, prof:1
I (1488) wifi: state: init -> auth (b0)
I (1488) wifi: state: auth -> assoc (0)
I (1488) wifi: state: assoc -> run (10)
I (1508) wifi: connected with STL, channel 11
I (1518) wifi: pm start, type: 1

[0;32mI (2208) event: sta ip: 10.0.1.181, mask: 255.255.255.0, gw: 10.0.1.1[0m
[0;32mI (2208) SWITCH: got ip:10.0.1.181[0m
[0;31mE (2208) nvs: nothing saved. key:30AEA421160CD0
[0m
[0;31mE (2208) nvs: nothing saved. key:30AEA421160CD1
[0m
[0;31mE (2218) nvs: nothing saved. key:30AEA421160CD2
[0m
[0;31mE (2218) nvs: nothing saved. key:30AEA421160CD3
[0m
[0;31mE (2228) nvs: nothing saved. key:30AEA421160CD4
[0m
[0;31mE (2228) nvs: nothing saved. key:30AEA421160CD5
[0m
[0;31mE (2238) nvs: nothing saved. key:30AEA421160CD6
[0m
[0;31mE (2248) nvs: nothing saved. key:30AEA421160CD7
[0m
[HTTPD] Connection 0x3ffbb558 from 10.0.1.179:49844
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49844: POST /pair-setup
[0;32mI (43278) SRP: setup_code:053-58-197
[0m
[0;32mI (46528) SRP: INITIALIZED
[0m
[INFO][PAIR-SETUP] init
[PAIR-SETUP] STATE:1[0;32mI (46528) SRP: setup_code:053-58-197
[0m
[0;32mI (49798) SRP: INITIALIZED
[0m
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49844: POST /pair-setup
[PAIR-SETUP] STATE:3[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49844: POST /pair-setup
[PAIR-SETUP] STATE:5[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_CLOSEConnection 0x3ffbb558 closed
[HTTPD] Connection 0x3ffbb838 from 10.0.1.179:49845
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49845: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49845: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49845: GET /accessories
[MAIN] LED READ
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49845: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffbb554,1073460564
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffbb838 closed
[HTTPD] Connection 0x3ffc942c from 10.0.1.185:59745
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59745: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] Connection 0x3ffc9690 from 10.0.1.179:49847
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59745: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59745: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: GET /characteristics
[MAIN] LED READ
[HAP][INFO] _decrypt end 88
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59745: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffca028,1073520680
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffc942c closed
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: GET /characteristics
[MAIN] LED READ
[HAP][INFO] _decrypt end 88
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: PUT /characteristics
[HAP][INFO] _decrypt end 189
[HTTPD] MG_EV_SEND. 1
[HTTPD] Connection 0x3ffc9360 from 10.0.1.158:65005
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65005: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65005: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65005: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65005: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffbd3b4,1073468340
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffc9360 closed
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49847: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffca0a0,1073520800
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffc9690 closed
[HTTPD] Connection 0x3ffbb80c from 10.0.1.185:59748
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59748: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59748: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59748: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59748: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:0D7CB7F0-B22C-44EE-98A0-89C4DE970151 KEY:�s�]�j+�3��aiZ��:W��fo+Y�SSI PERM:0x3ffbb7cc,1073461196
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffbb80c closed
[HTTPD] Connection 0x3ffca148 from 10.0.1.179:49848
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: PUT /characteristics
[MAIN] LED WRITE. 1
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] Connection 0x3ffcb138 from 10.0.1.158:65014
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65014: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65014: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65014: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65014: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65014: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffca9a8,1073523112
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffcb138 closed
[HTTPD] Connection 0x3ffcb1a4 from 10.0.1.158:65015
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65015: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65015: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65015: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65015: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65015: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: PUT /characteristics
[MAIN] LED WRITE. 0
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] Connection 0x3ffcbc5c from 10.0.1.185:59749
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59749: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59749: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59749: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] Connection 0x3ffcc390 from 10.0.1.162:52480
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.162:52480: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.162:52480: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.162:52480: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] Connection 0x3ffccf48 from 10.0.1.178:54632
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.178:54632: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.178:54632: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.178:54632: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59749: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59749: GET /characteristics
[MAIN] LED READ
[HAP][INFO] _decrypt end 88
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65015: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49848: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffcd6fc,1073534716
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffca148 closed
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59749: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:0D7CB7F0-B22C-44EE-98A0-89C4DE970151 KEY:�s�]�j+�3��aiZ��:W��fo+Y�SSI PERM:0x3ffc9f24,1073520420
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffcbc5c closed
[HTTPD] Connection 0x3ffcad28 from 10.0.1.185:59752
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59752: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59752: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65015: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffccef8,1073532664
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffcb1a4 closed
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59752: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59752: PUT /characteristics
[MAIN] LED WRITE. 1
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59752: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59752: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.185:59752: PUT /characteristics
[MAIN] LED WRITE. 0
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] Connection 0x3ffcaaf0 from 10.0.1.158:65052
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: GET /characteristics
[MAIN] LED READ
[HAP][INFO] _decrypt end 88
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: PUT /characteristics
[MAIN] LED WRITE. 1
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: PUT /characteristics
[MAIN] LED WRITE. 0
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_SEND. 1
[HTTPD] Connection 0x3ffcba50 from 10.0.1.179:49849
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49849: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49849: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49849: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49849: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffce5e4,1073538532
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffcba50 closed
[HTTPD] Connection 0x3ffcd70c from 10.0.1.179:49850
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49850: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 0
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49850: POST /pair-verify
[HTTPD] DEFAULT:102
[HTTPD] DEFAULT:100
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49850: GET /accessories
[HAP][INFO] _decrypt end 77
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49850: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49850: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49850: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.179:49850: PUT /characteristics
[HAP][INFO] _decrypt end 186
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_RECV
[INFO] HTTP request from 10.0.1.158:65052: POST /pairings
[PAIRINGS] STATE:1 METHOD:3
[PAIRINGS] ADD ID:E0BE7989-9819-41AB-9743-5EBDCCE0A090 KEY:Ц���� PERM:0x3ffcd834,1073535028
[HAP][INFO] _decrypt end 216
[HTTPD] MG_EV_SEND. 1
[HTTPD] MG_EV_CLOSEConnection 0x3ffcaaf0 closed
