### ISSUE TITLE
Identify button does not show up

### ISSUE THREAD

**Issue by yene** [younghyunjo/esp32-homekit#19]
**Steps:**
* build and run example Switch on ESP
* during pairing no option to identify

* Setup switch accessory in Homekit simulator
* during pairing you get the option to identify

I compared the configurations briefly but could not see why the switch example does not offer an identify.

**Comment by younghyunjo** [comment]
Hello.
I am not fully understand HAP`s identify protocol.

How can I fix my code?

**Comment by younghyunjo** [comment]
You are right.
But i remain the flag for easy to debug the code.

If you want to change Status flag, 
call **advertise_accessory_state_set**() API after paired with device.
