### ISSUE TITLE
Maximkulkin or younghyunjo

### ISSUE THREAD

**Issue by jukorp** [younghyunjo/esp32-homekit#25]
which one is better? Maximkulkin or younghyunjo

https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/esp32/led

**Comment by cduvenhorst** [comment]
That’s a question of taste and can’t be answered for you.

**Comment by cduvenhorst** [comment]
But ... someone reported here a month ago an obvious memory leak in JSON parsing and it is still not fixed. Memory Leaks are bad for HomeKit Devices which are supposed to run permanently.

**Comment by younghyunjo** [comment]
@jukorp 
I don`t know. Maybe you can test both.
