### ISSUE TITLE
help: LD error

### ISSUE THREAD

**Issue by EvanLyu** [younghyunjo/esp32-homekit#3]
I have some build error on windows and my mac.
I'm using latest sdk (esp-idf and components/arduino).

![image](https://user-images.githubusercontent.com/6142091/36803907-ecde87ee-1cf3-11e8-8b37-1d3fff80f12f.png)

Always show me undefined reference to 'wc_HKDF'
Can you give me any advice?

**Comment by EvanLyu** [comment]
And mongoose  library is upgrade to 6.11 to fixed some build error.

**Comment by jukorp** [comment]
I have the same error message.
Is it possible to work with homes? esp-idf includes the old version of lwip. perhaps 1.4.1

**Comment by younghyunjo** [comment]
Thank you for waiting me.
I wrote Build guide.
If you have any further problem, please ask me feel free.
