### ISSUE TITLE
Change license to Apache license v2

### ISSUE THREAD

**Issue by MalteJ** [younghyunjo/esp32-homekit#4]
GPL is not really usable for anything but non-commercial maker projects.
This library could get more attention if it is licensed under a BSD-like license like the Apache v2 license or MIT License.

**Comment by younghyunjo** [comment]
Thank you for your advice.
I will see the difference among GPL, Apache v2 and MIT and change it later.

**Comment by younghyunjo** [comment]
Changed to Apache license v2
