### ISSUE TITLE
"No Response" with iOS 14 devices

### ISSUE THREAD

**Issue by yujinakayama** [younghyunjo/esp32-homekit#51]
I've been using some accessories built with esp32-homekit for a while, but after updating my Apple devices to iOS/iPadOS 14 they appear as "No Response" in the Home app.

Is anyone experiencing the same issue?

**Comment by MacWyznawca** [comment]
Beter use oficial publik HomeKit SDK from Espressif?
https://mojmac.pl/2020/10/10/homekit-sdk-dla-esp32-i-esp8266-udostepniony-przez-espressif/

**Comment by yujinakayama** [comment]
Didn't know such great news!
I'll give it a try. Thanks!

**Comment by MacWyznawca** [comment]
Today news 😉  fresh deploy 😉

**Comment by yujinakayama** [comment]
I've confirmed esp-homekit-sdk works properly with iOS 14 👍
